version: '3'

services:
  nodejs:
    image: nodejs
    container_name: nodejs
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 3000:3000
    tty: true