version: '3'

services:
  nodejs:
    image: nodejs
    container_name: nodejs
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html/index.html:/var/www/html/index.html
    ports:
      - 80:80
    tty: true